package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"friend_graphql/graph/model"
)

// Comment is the resolver for the comment field.
func (r *mutationResolver) Comment(ctx context.Context) (*model.CommentMutation, error) {
	return &model.CommentMutation{}, nil
}

// Post is the resolver for the post field.
func (r *mutationResolver) Post(ctx context.Context) (*model.PostMutation, error) {
	return &model.PostMutation{}, nil
}

// CommentMutation returns CommentMutationResolver implementation.
func (r *Resolver) CommentMutation() CommentMutationResolver { return &commentMutationResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// PostMutation returns PostMutationResolver implementation.
func (r *Resolver) PostMutation() PostMutationResolver { return &postMutationResolver{r} }

type commentMutationResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type postMutationResolver struct{ *Resolver }
