package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"friend_graphql/graph/model"
	"friend_graphql/internal/server"
	"strings"
)

func PointerConvert(slicerPointer []*string) []string {
	postID := make([]string, 0, len(slicerPointer))
	for _, id := range slicerPointer {
		postID = append(postID, *id)
	}
	return postID
}

// Find is the resolver for the find field.
func (r *postQueryResolver) Find(ctx context.Context, obj *model.PostQuery, filter *model.PostFilter) (model.PostDataResult, error) {
	_, err := server.AuthorizationCheck(ctx)
	if err != nil {
		return model.UnauthorizedError{Message: err.Error()}, nil
	}
	postID := PointerConvert(filter.Data.ID)
	fmt.Println(postID)
	hashtags := strings.Split(*filter.Data.Hashtags, "#")
	//Todo: дописать директиву чтобы можно было доставать данные
	//posts,err:=r.PostCommentDomain.FeedGetPosts(postID)
	//if err!=nil{
	//	return model.InternalErrorProblem{Message: err.Error()}, nil
	//}
	posts, err := r.PostCommentDomain.FeedGetPostsWithHashtag(hashtags, filter.Limit, filter.Offset, "")
	return model.PostFindOk{Posts: posts}, nil
}
