package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"friend_graphql/graph/model"
)

// Create is the resolver for the create field.
func (r *postMutationResolver) Create(ctx context.Context, obj *model.PostMutation, input model.NewPost) (model.PostCreateResult, error) {
	userID, err := AuthorizationCheck(ctx)
	if err != nil {
		return model.UnauthorizedError{Message: err.Error()}, nil
	}
	result, err := r.PostDomain.UploadPostKafka(&input, userID)
	if err != nil {
		return model.UnauthorizedError{Message: err.Error()}, nil
	}
	return model.PostCreateOk{ArticleID: result}, nil
}
