package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"friend_graphql/graph/model"
	"friend_graphql/internal/server"
)

// Find is the resolver for the find field.
func (r *postQueryResolver) Find(ctx context.Context, obj *model.PostQuery, filter *model.PostFilter) (model.PostDataResult, error) {
	_, err := server.AuthorizationCheck(ctx)
	if err != nil {
		return model.UnauthorizedError{Message: err.Error()}, nil
	}
	
}
