package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"friend_graphql/graph/model"
)

// CommentChild is the resolver for the commentChild field.
func (r *commentResolver) CommentChild(ctx context.Context, obj *model.Comment, limit *int32, offset *int32) ([]*model.Comment, error) {
	commentID := obj.CommentID
	comments, err := r.CommentDomain.GetComment(commentID, *limit, *offset)
	if err != nil {
		return nil, err
	}
	return comments, nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *model.Post, limit *int32, offset *int32) ([]*model.Comment, error) {
	//Todo: подумать о проверке авторизации
	postID := obj.PostID
	comments, err := r.CommentDomain.GetComment(postID, *limit, *offset)
	if err != nil {
		return nil, err
	}
	return comments, nil
}

// Friends is the resolver for the friends field.
func (r *userResolver) Friends(ctx context.Context, obj *model.User, limit *int32, offset *int32) ([]*model.User, error) {
	friends, err := r.UserDomain.GetUserFriendSubscriber(obj, ctx, *limit, *offset, true)
	if err != nil {
		return nil, err
	}
	return friends, nil
}

// Subscribes is the resolver for the subscribes field.
func (r *userResolver) Subscribes(ctx context.Context, obj *model.User, limit *int32, offset *int32) ([]*model.User, error) {
	subscribers, err := r.UserDomain.GetUserFriendSubscriber(obj, ctx, *limit, *offset, true)
	if err != nil {
		return nil, err
	}
	return subscribers, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *model.User, limit *int32, offset *int32) ([]*model.Post, error) {
	//Todo: по id user
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type commentResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
