package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"friend_graphql/graph/model"
)

// Find is the resolver for the find field.
func (r *userFindResolver) Find(ctx context.Context, obj *model.UserFind, input *model.UserID) (model.UserFindResult, error) {
	panic(fmt.Errorf("not implemented: Find - find"))
}
