package runtime

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"friend_graphql/graph/model"
	"friend_graphql/internal/server"
)

// Find is the resolver for the find field.
func (r *userFindResolver) Find(ctx context.Context, obj *model.UserFind, input *model.UserID) (model.UserFindResult, error) {
	userID, err := server.AuthorizationCheck(ctx)
	if err != nil {
		return model.UnauthorizedError{Message: err.Error()}, nil
	}
	user, err := r.UserDomain.GetUserInfo(userID)
	if err != nil {
		return model.InternalErrorProblem{Message: err.Error()}, nil
	}
	return model.UserFindOk{User: user}, nil
}
