package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"friend_graphql/graph/model"
)

// Create is the resolver for the create field.
func (r *commentMutationResolver) Create(ctx context.Context, obj *model.CommentMutation, input model.NewComment) (model.CommentCreateResult, error) {
	panic(fmt.Errorf("not implemented: Create - create"))
}

// CommentMutation returns CommentMutationResolver implementation.
func (r *Resolver) CommentMutation() CommentMutationResolver { return &commentMutationResolver{r} }

type commentMutationResolver struct{ *Resolver }
