package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"fmt"
	"friend_graphql/graph/model"
)

// Find is the resolver for the find field.
func (r *postQueryResolver) Find(ctx context.Context, obj *model.PostQuery, filter *model.PostFilter) (model.PostDataResult, error) {
	panic(fmt.Errorf("not implemented: Find - find"))
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context) (*model.PostQuery, error) {
	return &model.PostQuery{}, nil
}

// PostQuery returns PostQueryResolver implementation.
func (r *Resolver) PostQuery() PostQueryResolver { return &postQueryResolver{r} }

type postQueryResolver struct{ *Resolver }
