// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID        string    `json:"id"`
	AuthorID  string    `json:"authorID"`
	TagIDS    []*string `json:"tagIDS,omitempty"`
	Content   string    `json:"content"`
	CreatedAt *string   `json:"createdAt,omitempty"`
	Watched   *int32    `json:"watched,omitempty"`
	Likes     *int32    `json:"likes,omitempty"`
}

type Query struct {
}

type User struct {
	ID            string    `json:"id"`
	FirstName     string    `json:"firstName"`
	SecondName    string    `json:"secondName"`
	MainImgURL    string    `json:"mainImgUrl"`
	Images        []*string `json:"images,omitempty"`
	BirthDate     *string   `json:"birthDate,omitempty"`
	Education     *string   `json:"education,omitempty"`
	Country       *string   `json:"country,omitempty"`
	City          *string   `json:"city,omitempty"`
	FriendIDs     []*string `json:"friendIDs,omitempty"`
	PostIDs       []*string `json:"postIDs,omitempty"`
	SubscribesIDs []*string `json:"subscribesIDs,omitempty"`
	Friends       []*User   `json:"friends,omitempty"`
	Subscribes    []*User   `json:"subscribes,omitempty"`
	Posts         []*Post   `json:"posts,omitempty"`
}
